tasks:
  - name: Running Project
    init: npm install && gp sync-done npm-install
    command: npm run start
  - name: Running Storybook
    init: gp sync-await npm-install
    command: npm run storybook
  - name: Running Jest test
    init: gp sync-await npm-install
    command: npm run test
ports:
  - name: Web App
    description: Main React App
    port: 3000
    onOpen: open-browser
  - name: Storybook
    description: Storybook Component Details
    port: 6006
    onOpen: open-browser